name: Generate Snake (Dark Only)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Clean old SVGs
        run: |
          rm -rf output
          mkdir output

      - name: Generate dark-only snake
        uses: Platane/snk@v3
        with:
          github_user_name: Aaxhirrr
          outputs: |
            ./output/github-contribution-grid-snake-dark.svg
        env:
          SNK_THEME: dark

      - name: Deploy snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
