name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Aaxhirrr
          outputs: |
            ./output/github-contribution-grid-snake-dark.svg
          args: >
            --snake-color '#00FF00'
            --dot-color '#66CCFF,#00FFAA,#AA00FF,#FF00AA,#3300FF'
            --output-format svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
