name: Generate Custom Neon Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Aaxhirrr
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg
          snake_format: svg
          color_snake: '#00FFAA'  # neon green
          color_dots: '#00ffff, #00cc99, #ff00ff, #9900ff'  # AGI-like colors

      - name: Inject dark purple cyber grid and glow effect
        run: |
          SVG=output/github-contribution-grid-snake-dark.svg
          TMP=output/tmp.svg

          echo '<?xml version="1.0" encoding="UTF-8"?>' > $TMP
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">' >> $TMP
          echo '<defs>' >> $TMP
          echo '<filter id="glow" x="-50%" y="-50%" width="200%" height="200%">' >> $TMP
          echo '  <feGaussianBlur in="SourceGraphic" stdDeviation="2" result="blur" />' >> $TMP
          echo '  <feMerge>' >> $TMP
          echo '    <feMergeNode in="blur" />' >> $TMP
          echo '    <feMergeNode in="SourceGraphic" />' >> $TMP
          echo '  </feMerge>' >> $TMP
          echo '</filter>' >> $TMP
          echo '</defs>' >> $TMP
          echo '<rect width="100%" height="100%" fill="#1a0033" />' >> $TMP

          grep "<path" $SVG | sed 's/<path /<path filter="url(#glow)" /' >> $TMP

          echo '</svg>' >> $TMP
          mv $TMP $SVG

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
